# Site configuration
domain: "http://songroger.win"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://songroger.github.io/" # the base hostname & protocol for your site
permalink: /:title/
avatar: https://thumbnail0.baidupcs.com/thumbnail/c1f40c8e16737946d3ba327bbe9132bd?fid=973427439-250528-967813936545243&time=1519639200&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-hUj9P%2B2ayIdUUb4jMAItjt6OLwY%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=1316386483269084233&dp-callid=0&size=c710_u400&quality=100&vuk=-&ft=video
about: http://7xof48.com1.z0.glb.clouddn.com/about.jpg
favicon: http://7xof48.com1.z0.glb.clouddn.com/favicon.png
basecss: 
# Theme specific configuration
title: guoqingcun
description: >
  Hi there, My name is Luozhan.Song, usually I use "songroger" as my ID everywhere.
  I was born and raised in Hunan China. 
  I'm really fond of beautiful design, drawing etc.

# Contact and social media links
twitter_username: guoqingcun
github_username: guoqingcun
facebook_username: qingcun.guo
instagram_username: guoqingcun
linkedin_username: guoqingcun

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false
# disqus_account: songroger

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
